### ISSUE TITLE
文字标签功能如何实现？

### ISSUE THREAD

**Issue by dreamgo** [TuSDK/TuSDK-for-iOS-demo#1]
在官网看到的电商类示例图片中 有文字标签功能，在demo中并未找到，请问可以实现么？ 谢谢
<img width="507" alt="screen shot 2016-03-21 at 7 18 22 pm" src="https://cloud.githubusercontent.com/assets/6346870/13937246/d544dc16-ef99-11e5-9cba-53ecca1c2399.png">

**Comment by idealhack** [comment]
Hi，网站上已有注明「正在开发中」，因为人脸和直播两块的工作量较大，目前标签功能的完成时间尚不明确。感谢您对 TuSDK 的关注。

**Comment by dreamgo** [comment]
这个文字标签以后是单独的动画还是像贴纸一样一起渲染到图片中的？

**Comment by idealhack** [comment]
应该是分离的。
