### ISSUE TITLE
如何显示adjumentView or filtersView

### ISSUE THREAD

**Issue by dreamgo** [TuSDK/TuSDK-for-iOS-demo#2]
在一个view上自定义了一个button，如何可以像照片美化编辑组件中那样显示adjusmentView 或者filtersview  ？

**Comment by dreamgo** [comment]
关于custom ui这块儿 希望能有更详细的文档出来。

**Comment by idealhack** [comment]
您好，技术问题请在我们网站控制台的反馈处提交，会有专门工程师解答，谢谢。
