### ISSUE TITLE
关于UIKit类拓展中方法命名的小建议

### ISSUE THREAD

**Issue by Leo934524** [TuSDK/TuSDK-for-iOS-demo#3]
最近偶然接触贵公司的sdk，上手初发现其中对于一些常用类拓展中的方法名与项目中自己拓展或使用的方法名大量冲突，例如 UIView 中 initView 方法，NSDate 中 year month day 等方法，感觉此类拓展一般项目很大概率会有同名方法或拓展，所以认为是否方法前加前缀更妥当

**Comment by idealhack** [comment]
您好，感谢您对 TuSDK 的关注和建议。

扩展类方法命名我们在最近几个版本中已经改了不少，类似 `UIView` 的 `initView` 我们会考虑继续加前缀，而类似 `year` 这类返回结果不太可能有差别的方法，似乎没有加前缀的必要。

**Comment by Leo934524** [comment]
谢谢您的回复。
其实，我觉得对于类似 year 这类方法也是有加前缀的必要的，个人看法如下：
- 为了解决两边的冲突，就必须删除我们的方法，或者将我们的方法添加前缀，对于删除的情况，若将来不再需要使用此库，还需将其添加回来，较为麻烦。
- 对于其他三方库，如果对于此类进行拓展，且都使用同样的方法名不加前缀，是否不妥呢

**Comment by idealhack** [comment]
了解您的顾虑了，我们会在下一版本中修复这些问题。

在此之前，请您先加上自己的前缀作为暂时方案。
