### ISSUE TITLE
处理后的图片会在哪个接口中得到？我没有找到获取图片的接口与地方

### ISSUE THREAD

**Issue by Yulei-Duan** [TuSDK/TuSDK-for-iOS-demo#5]
处理后的图片会在哪个接口中得到？我没有找到获取图片的接口与地方，希望得到您的解答。

**Comment by idealhack** [comment]
请阅读 https://tusdk.com/docs/ios/editor-usage 中的「获取编辑结果图片」一节。

今后使用有问题请在控制台的反馈处提交。
